# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tulo/departments/v1/department.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'
require 'tulo/common/v1/response_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tulo/departments/v1/department.proto", :syntax => :proto3) do
    add_message "tulo.departments.v1.DepartmentsResponse" do
      repeated :departments, :message, 1, "tulo.departments.v1.Department"
    end
    add_message "tulo.departments.v1.UpsertDepartmentRequest" do
      optional :department, :message, 1, "tulo.departments.v1.Department"
    end
    add_message "tulo.departments.v1.UpsertDepartmentResponse" do
      optional :department, :message, 1, "tulo.departments.v1.Department"
    end
    add_message "tulo.departments.v1.DepartmentIdRequest" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
    end
    add_message "tulo.departments.v1.DepartmentResponse" do
      optional :department, :message, 1, "tulo.departments.v1.Department"
    end
    add_message "tulo.departments.v1.Department" do
      optional :id, :message, 1, "google.protobuf.Int64Value"
      optional :department_name, :message, 2, "google.protobuf.StringValue"
      optional :parent_department_id, :message, 3, "google.protobuf.Int64Value"
      optional :mgr_id, :message, 4, "google.protobuf.Int64Value"
      optional :description, :message, 5, "google.protobuf.StringValue"
      optional :created_at, :message, 6, "google.protobuf.StringValue"
      optional :updated_at, :message, 7, "google.protobuf.StringValue"
    end
  end
end

module Tulo
  module Departments
    module V1
      DepartmentsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.departments.v1.DepartmentsResponse").msgclass
      UpsertDepartmentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.departments.v1.UpsertDepartmentRequest").msgclass
      UpsertDepartmentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.departments.v1.UpsertDepartmentResponse").msgclass
      DepartmentIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.departments.v1.DepartmentIdRequest").msgclass
      DepartmentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.departments.v1.DepartmentResponse").msgclass
      Department = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tulo.departments.v1.Department").msgclass
    end
  end
end
